name = 'img'
workers_dev = true
type = 'webpack'
webpack_config = 'webpack.config.js'
compatibility_date = '2021-12-14'


[env.dev]

  [env.dev.vars]
  ENV = 'dev'
  TTL = 60
  DEDUPE = false

  [[env.dev.kv_namespaces]]
  binding = 'ImageKV'
  preview_id = '873d3300fc41484fbce49b11d533a6b8'


[env.prod]

  [env.prod.vars]
  ENV = 'prod'
  USERNAME = 'byg'
  PASSWORD = '1234'
  TTL = 3600
  DEDUPE = false

  [[env.prod.kv_namespaces]]
  binding = 'ImageKV'
  id = '873d3300fc41484fbce49b11d533a6b8'

  [env.prod.site]
  bucket = '../app/dist'
  entry-point = 'workers-site'


[dev]
ip = '127.0.0.1'
port = 8787
